### ISSUE TITLE
Twig_Error_Syntax - Unknown "path_for" function in . . . 

### ISSUE THREAD

**Issue by phoenixjaymes** [slimphp/Twig-View#62]
I've read some of the closed issues and it seems that no one, is actually having an issue using path_for. I have double and triple check for typos. 

`{{ path_for('home', {'name': 'home'}) }}`

Everything else is working great. Any ideas what is going on?

**Comment by nisbeti** [comment]
Check how your home route is setup. It should have '/{name}' as the path or
something like that. Also, the home route should have ->setName('home').
Also make sure that there is only one route named home. These are some
common issues.
If you have slip error reporting switched on the bug is usually quite
explicitly stated.
Finally, how have you set up Twig extension, to ensure it has access to the
Slim's router?

**Comment by akrabat** [comment]
Have you added the `Slim\Views\TwigExtension` extension?

**Comment by phoenixjaymes** [comment]
I forgot the extensions, that's for the help.
