### ISSUE TITLE
Raising Issues for confusing version compatibility

### ISSUE THREAD

**Issue by shahariaazam** [slimphp/Twig-View#77]
PHP Parse error:  syntax error, unexpected '.' in /base/data/home/apps/b~previewtechs-cloud/slim-app-skeleton:20170224t205746.399418087592248769/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1552

`"twig/twig": "^1.18|^2.0",` I guess it is causing some trouble. Recently I just ran my application on my local machine with PHP 7.1. It works well but when I just deployed that  app to Google App Engine (PHP 5.5.9 environment) then it raised error.

```php
PHP Parse error:  syntax error, unexpected '.' in /base/data/home/apps/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1552
```
So I am pretty sure it's because of PHP versioning. So if anybody want to avoid the issue, they need to manually add main `"twig/twig"` package in their installation. Otherwise, somebody can face compatibility issue after app deployment.

I think, we can add a small note in `Readme.md` file.

**Comment by akrabat** [comment]
I would prefer to see the `platform` setting documented in the README.

**Comment by stof** [comment]
The issue is about the way you used Composer. If you run `composer update` on PHP 7.1, composer will **not** ensure compatibility with PHP 5.5 when installing dependencies.
If you want a lock file compatible with PHP 5.5, you have 2 options:

- run `composer update` on PHP 5.5
- use the `platform` configuration setting of composer to overwrite the PHP version being considered by Composer.
